version: '3'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: product_db
